### PR TITLE
added support for opensuse

### PR DESCRIPTION
**Pull request by andtherand**
Hey there again :),

it's me again. I've added support for openSuse 13.2. I have also changed the names of tasks - sorry for that, I was kind of eager.

Cherio Andy!

### CODE REVIEW

**Comment by franklinkim** [comment]
hi, I implemented you request a little bit different but i should do the trick for ya :)

(...and nice try with the task names ;P)

**Comment by andtherand** [comment]
No problem thanks! Now I don't have to rely on my local copy anymore :].

I really like your approach! I was not aware that there was "ansible_pkg_mgr". That way all platforms should be supported. 
Do you have any source for that "special" variable?

**Comment by franklinkim** [comment]
you can see this variable and others facts about the environment here: [Information discovered from systems: Facts](http://docs.ansible.com/ansible/playbooks_variables.html#information-discovered-from-systems-facts)

**Comment by andtherand** [comment]
Alright, of course I've visited that page, but haven't checked all values! Anyways I think it's a really nice and elegant approach to do it this way!

**Pull request closed without merging**
